"""Tests for ``z4j_brain.auth.passwords``."""

from __future__ import annotations

import secrets
import time

import pytest

from z4j_brain.auth.passwords import PasswordError, PasswordHasher
from z4j_brain.settings import Settings


@pytest.fixture
def hasher() -> PasswordHasher:
    s = Settings(
        database_url="sqlite+aiosqlite:///:memory:",
        secret=secrets.token_urlsafe(48),  # type: ignore[arg-type]
        session_secret=secrets.token_urlsafe(48),  # type: ignore[arg-type]
        environment="dev",
        # Smaller argon2 cost for fast tests - still real argon2id.
        argon2_time_cost=1,
        argon2_memory_cost=8192,
    )
    return PasswordHasher(s)


class TestRoundTrip:
    def test_hash_then_verify(self, hasher: PasswordHasher) -> None:
        h = hasher.hash("correct horse battery staple 9")
        assert hasher.verify(h, "correct horse battery staple 9") is True

    def test_verify_wrong_password(self, hasher: PasswordHasher) -> None:
        h = hasher.hash("right one 9")
        assert hasher.verify(h, "wrong one") is False

    def test_verify_corrupt_hash_does_not_raise(
        self, hasher: PasswordHasher,
    ) -> None:
        # Total nonsense - verify must return False, never raise.
        assert hasher.verify("not-a-real-hash", "anything") is False

    def test_verify_empty_hash_does_not_raise(
        self, hasher: PasswordHasher,
    ) -> None:
        assert hasher.verify("", "anything") is False


class TestDummyHash:
    def test_dummy_hash_is_real_argon2(self, hasher: PasswordHasher) -> None:
        # The dummy hash starts with $argon2id$.
        assert hasher.dummy_hash.startswith("$argon2id$")

    def test_dummy_hash_changes_per_process(self) -> None:
        s = Settings(
            database_url="sqlite+aiosqlite:///:memory:",
            secret="x" * 48,  # type: ignore[arg-type]
            session_secret="y" * 48,  # type: ignore[arg-type]
            environment="dev",
            argon2_time_cost=1,
            argon2_memory_cost=8192,
        )
        h1 = PasswordHasher(s)
        h2 = PasswordHasher(s)
        # Different random secrets at construction → different hashes.
        assert h1.dummy_hash != h2.dummy_hash

    def test_verify_dummy_hash_with_random_input(
        self, hasher: PasswordHasher,
    ) -> None:
        # Dummy is a hash of a random string we don't know - verify
        # against a guess MUST return False.
        assert hasher.verify(hasher.dummy_hash, "any guess") is False


class TestTiming:
    """Wrong-user vs wrong-password timing must be comparable.

    The dummy hash exists exactly to mask username enumeration via
    timing. We assert that verifying the dummy hash takes within
    50% of verifying a real hash (very loose because CI is noisy).
    """

    def test_dummy_and_real_take_similar_time(
        self, hasher: PasswordHasher,
    ) -> None:
        real = hasher.hash("real password 9")

        def measure(target: str) -> float:
            t0 = time.monotonic()
            for _ in range(5):
                hasher.verify(target, "wrong guess")
            return time.monotonic() - t0

        real_time = measure(real)
        dummy_time = measure(hasher.dummy_hash)
        # Looser: 5x ratio. CI noise + small argon2 cost in tests.
        assert real_time / dummy_time < 5
        assert dummy_time / real_time < 5


class TestNeedsRehash:
    def test_freshly_hashed_does_not_need_rehash(
        self, hasher: PasswordHasher,
    ) -> None:
        h = hasher.hash("anything 9")
        assert hasher.needs_rehash(h) is False

    def test_corrupt_hash_treated_as_needing_rehash(
        self, hasher: PasswordHasher,
    ) -> None:
        assert hasher.needs_rehash("not-a-real-hash") is True


class TestPolicy:
    def test_too_short(self, hasher: PasswordHasher) -> None:
        with pytest.raises(PasswordError) as exc:
            hasher.validate_policy("short1")
        assert exc.value.code == "password_too_short"

    def test_too_long(self, hasher: PasswordHasher) -> None:
        with pytest.raises(PasswordError) as exc:
            hasher.validate_policy("a1" * 200)
        assert exc.value.code == "password_too_long"

    def test_no_letter(self, hasher: PasswordHasher) -> None:
        with pytest.raises(PasswordError) as exc:
            hasher.validate_policy("123456789012345")
        assert exc.value.code == "password_too_simple"

    def test_no_digit(self, hasher: PasswordHasher) -> None:
        with pytest.raises(PasswordError) as exc:
            hasher.validate_policy("abcdefghijkl")
        assert exc.value.code == "password_too_simple"

    def test_in_breach_list(self, hasher: PasswordHasher) -> None:
        # Summer2024! satisfies 3-of-4 character classes (upper, lower,
        # digit, symbol) but is generated by the pattern denylist
        # (audit A3 expansion).
        with pytest.raises(PasswordError) as exc:
            hasher.validate_policy("Summer2024!")
        assert exc.value.code == "password_in_breach_list"

    def test_in_breach_list_case_insensitive(
        self, hasher: PasswordHasher,
    ) -> None:
        with pytest.raises(PasswordError) as exc:
            hasher.validate_policy("WELCOME2024!")
        assert exc.value.code == "password_in_breach_list"

    def test_three_of_four_character_classes_required(
        self, hasher: PasswordHasher,
    ) -> None:
        # Audit A3: "letter + digit only" no longer passes.
        with pytest.raises(PasswordError) as exc:
            hasher.validate_policy("abcdefgh1")
        assert exc.value.code == "password_too_simple"

    def test_acceptable_password(self, hasher: PasswordHasher) -> None:
        # Four classes: lower, upper, digit, symbol.
        hasher.validate_policy("Correct-Horse-9-Battery!")
